import turtle
turtle.shape("turtle")
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.pencolor("red")
turtle.pensize(5)
turtle.done()